//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class examenEntities : DbContext
    {
        public examenEntities()
            : base("name=examenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<P_Clientes> P_Clientes { get; set; }
        public virtual DbSet<P_Detalle> P_Detalle { get; set; }
        public virtual DbSet<P_Facturas> P_Facturas { get; set; }
        public virtual DbSet<P_Productos> P_Productos { get; set; }
        public virtual DbSet<P_Usuario> P_Usuario { get; set; }
    }
}
