//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamenP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public P_Facturas()
        {
            this.P_Detalle = new HashSet<P_Detalle>();
        }
    
        public int Id_Factura { get; set; }
        public Nullable<int> No_Factura { get; set; }
        public Nullable<int> Cliente_id { get; set; }
        public Nullable<int> Usuario_id { get; set; }
    
        public virtual P_Clientes P_Clientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<P_Detalle> P_Detalle { get; set; }
    }
}
